# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_srcs: [2, 3, 4, 5]
  bn_chan: 128
  hid_size: 128
  chunk_size: 100
  hop_size: 50
  n_repeats: 8
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
  use_mulcat: true
# Training config
training:
  epochs: 200
  batch_size: 3
  num_workers: 3
  half_lr: yes
  lr_decay: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.00000
# Data config
data:
  dataset: "/ws/ifp-10_3/hasegawa/junzhez2/asteroid/dataset"
  train_dir: "{}speakers/wav8k/min/tr"
  valid_dir: "{}speakers/wav8k/min/cv"
  task: sep_clean
  sample_rate: 8000
  seglen: 4.0
  minlen: 2.0
loss:
  lambda: 0.05